apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudeco-deployment
  labels:
    app: cloudeco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudeco
  template:
    metadata:
      labels:
        app: cloudeco
    spec:
      containers:
        - name: cloudeco
          image: gcr.io/project-75f92f7c-c9ed-4db3-9cc/cloudeco:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1.0"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
