apiVersion: v1
kind: Service
metadata:
  name: cloudeco-service
  labels:
    app: cloudeco
spec:
  type: LoadBalancer
  selector:
    app: cloudeco
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
